crudproject2/crudproject2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('studentapp.urls')),
]

crudproject2/studentapp/urls.py
from django.urls import URLPattern, re_path as path
from django.urls import path
from studentapp import views
app_name = 'studentapp'

urlpatterns= [
    path('',views.home, name='home'),
    path('signup/' ,views.user_sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.user_profile, name='profile'),    
    path('logout/', views.user_logout, name='logout'),
    
    path('userupdate/<int:id>', views.user_info_update, name='userupdate'),
    path('userchangepass/', views.user_change_pass, name='userchangepass'),
    
    path('addstudent/', views.addstudent, name='addstudent'),
    path('studentdetails/', views.student_details, name='studentdetails'), 
    path('updatestudent/<int:id>', views.update_student, name='updatestudent'), 
    path('deletestudent/<int:id>', views.delete_student, name='deletestudent'),  

]

crudproject2/studentapp/models.py
from django.db import models

# Create your models here.

class StudentDetails(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=40)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    class_name = models.IntegerField()
    result = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        return str(self.name)


crudproject2/studentapp/forms.py
from dataclasses import fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from studentapp import models

class SignUpForm(UserCreationForm):
    class Meta:
        
        #password1  =forms.TextInput(widget=forms.TextInput(attrs={'class' : 'form-control' , 'type':'password'}))
        model = User
        fields = ['username' , 'first_name','last_name','email','password1','password2']

        widgets = {
            'username' : forms.TextInput(attrs={'class':'form-control'}),
            'first_name' : forms.TextInput(attrs={'class':'form-control'}),
            'last_name' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'password1' : forms.PasswordInput(attrs={'class':'form-control','type':'password'}), # this field is  from UserCreationForm
           
            #'password1' : forms.TextInput(attrs={'class':'form-control','type':'password'}),

            'password2' : forms.PasswordInput(attrs={'class':'form-control'}),  # from UserCreationForm 
            
        }


class AddStudentForm(forms.ModelForm):
    class Meta:
        model = models.StudentDetails
        fields = "__all__" 
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            'phone' : forms.TextInput(attrs={'class':'form-control'}),
            'address' : forms.TextInput(attrs={'class':'form-control'}),
            'class_name' : forms.NumberInput(attrs={'class':'form-control'}), 
            'result' : forms.NumberInput(attrs={'class':'form-control'}),  
              
        }

class UserInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        widgets = {
            'username' : forms.TextInput(attrs={'class':'form-control'}),
            'first_name' : forms.TextInput(attrs={'class':'form-control'}),
            'last_name' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            
        }



crudproject2/studentapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
#from django.contrib.auth import authenticate,login,logout,update_session_auth_hash
from django.contrib import messages
from .models import *
# Create your views here.

def home(request):
    dict = {'title':'Home Page'}
    return render(request,'studentapp/home.html' , context=dict)
  
def user_sign_up(request):
    
    if request.method=='POST':
        fm = SignUpForm(request.POST)
        if fm.is_valid():
            fm.save()
            fm = SignUpForm()
            messages.success(request,"Account Created Successfully!!!")
        else:
            messages.error(request,"Your data is not valid. Enter valid data carefully!")

    else:
        fm = SignUpForm()

    dict = {'form':fm , 'title':'Sign Up'}
    return render(request,'studentapp/signup.html' , context=dict)
   
   

def user_login(request):
    if not request.user.is_authenticated:

        if request.method=='POST':
            fm = AuthenticationForm(request=request , data=request.POST)
            if fm.is_valid():
                uname = fm.cleaned_data['username']
                upass = fm.cleaned_data['password']
                user = authenticate(username=uname, password=upass)

                if user is not None:
                    login(request,user)
                    return HttpResponseRedirect('/profile/')
            else:
                messages.error(request,"Enter correct username and password!!!")
            
        else:
            fm = AuthenticationForm()
    
        dict = {'form':fm , 'title':'Login'}
  
        return render(request,'studentapp/login.html' , context=dict)
    else:
        return HttpResponseRedirect('/profile/')



def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/login/')
    else:
        return HttpResponseRedirect('/login/')


def user_profile(request):
    if request.user.is_authenticated:
        user = request.user
        dict = {'title':'Profile Page','user':user}
        return render(request,'studentapp/profile.html' , context=dict)
    else:
        return HttpResponseRedirect('/login/')

def user_info_update(request,id):
    if request.user.is_authenticated:

        user_info = User.objects.get(pk=id)
        fm = UserInfoUpdateForm(instance=user_info)

        if request.method=='POST':
            fm = UserInfoUpdateForm(request.POST,instance=user_info)
            if fm.is_valid():
                fm.save(commit=True)
                return HttpResponseRedirect('/profile/')
        
        dict = {'form' :fm}
        return render(request,'studentapp/userprofileupdate.html',context=dict)
    else:
        return HttpResponseRedirect('/login/')



def user_change_pass(request):
    if request.user.is_authenticated:
        #return HttpResponse("correct path man!!!")
        
        if request.method=='POST':

            fm = PasswordChangeForm(user=request.user , data = request.POST)
            if fm.is_valid():
                fm.save()  
                #update_session_auth_hash(request , fm.user)
                return HttpResponseRedirect('/profile/')
        else:
            fm = PasswordChangeForm(user = request.user)
        return render(request,'studentapp/userchangepass.html' , {'form':fm})
        
    else:
        return HttpResponseRedirect('/login/')


   
def student_details(request):
    if request.user.is_authenticated:
        students_info = StudentDetails.objects.all()
        dict = {'title':'student details','students_info':students_info}
        return render(request,'studentapp/studentdetails.html' , context=dict)
    else:
        return HttpResponseRedirect('/login/')


def addstudent(request):
    if request.user.is_superuser:

        if request.method=='POST':
            fm =AddStudentForm(request.POST)
            if fm.is_valid():
                fm.save(commit=True)
                return HttpResponseRedirect('/studentdetails/')
            
        else:
            fm = AddStudentForm()

        dict = {'title':'add student', 'form':fm}
        return render(request,'studentapp/addstudent.html' , context=dict)
    
    else:
        return HttpResponseRedirect('/') # go to home page
        

def update_student(request,id):
    if request.user.is_authenticated:
        std_info = StudentDetails.objects.get(pk=id)
        if request.method=='POST':
            fm = AddStudentForm(request.POST,instance=std_info)
            if fm.is_valid():
                fm.save(commit=True)
                return HttpResponseRedirect('/studentdetails/')
        else:
            fm = AddStudentForm(instance=std_info)
        dict = {'form':fm}
        return render(request,'studentapp/updatestudent.html',context=dict)
    else:
        return HttpResponseRedirect('/login/')

def delete_student(request,id):
    std = StudentDetails.objects.get(pk=id)
    std.delete()
    return HttpResponseRedirect('/studentdetails/')

crudproject2/templates/studentapp/addstudent.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">Add Student Page</h1>


<form action="" method="POST">
    {%csrf_token %} {% for fm in form %} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> {%endfor%}
    <input type="submit" value="Add Student" class="btn btn-success btn-sm my-3">
</form>



<br> {% endblock body_block %}

crudproject2/templates/studentapp/base.html
<!doctype html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <title> {{title}} </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'studentapp:home' %}">StudentApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:home' %}">Home</a>
                </li>


                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:login' %}">Login</a>
                </li>

                {%endif%} 
                
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:addstudent' %}">Add Student</a>
                </li>
                {%endif%} 
                
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:studentdetails' %}">Student Details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'studentapp:logout' %}">Logout</a>
                </li>

                {%endif%}


            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %} {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>

</body>

</html>

crudproject2/templates/studentapp/home.html
{% extends 'studentapp/base.html' %} 
{% load static  %}

{% block body_block %}

<h1 class="text-center my-3">This is Home page</h1>



<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa amet quibusdam dolores dolore, dignissimos placeat eos. Deleniti assumenda nostrum incidunt iste cupiditate animi dignissimos. Fugiat expedita rerum, veritatis perferendis provident esse culpa
    quae voluptates quod excepturi libero eligendi dolorem consectetur incidunt commodi soluta laudantium! Ipsa, blanditiis sequi beatae placeat quibusdam provident dignissimos hic autem magnam fugit labore quam odio numquam, at consequuntur fuga aut
    iusto, distinctio deserunt error laudantium consectetur! Deleniti, aliquid velit perspiciatis id nobis repellat, repudiandae facilis alias est n.</p>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, obcaecati inventore nam ipsum aperiam sunt repellat quod animi aspernatur cumque consectetur. Aliquid accusamus id asperiores! Laborum, recusandae consequatur tenetur neque ipsum hic ipsam
    blanditiis dignissimos, vitae cum exercitationem dolore cupiditate similique iusto alias quos nisi quaerat fugiat voluptates reprehenderit sint non nihil sed. Ut velit numquam laboriosam commodi explicabo facere illo! Minima porro eum aliquam reprehenderit
    debitis est magnam perspiciatis vitae laborum, possimus veniam? Facere ratione quaerat reiciendis molestiae quam.


    
</p>




{% endblock body_block %}

crudproject2/templates/studentapp/login.html
{% extends 'studentapp/base.html' %} {% block body_block %} {%if messages%}
<div class="alert alert-danger alert-dismissible mb-3">
    <button type="button" class="close" data-dismiss="alert">&times;</button> {%for message in messages %} {{message}} {%endfor%}
</div>
{%endif%}
<h1 class="text-center my-3">Login Page</h1>

<form action="" method="POST">
    {%csrf_token %} 
    {% for fm in form %} 
    {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br>
     {%endfor%}
    <input type="submit" value="Login" class="btn btn-success btn-sm my-2">
</form>

<a href=" {%  url 'studentapp:signup' %}  " class="btn btn-success btn-sm">Signup</a>


<br> {% endblock body_block %}

crudproject2/templates/studentapp/profile.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">Profile Page</h1>
<h3 class="mb-5">Welcome {{user.username}} </h3>

<table class="table ">
    <tbody>
        <tr>
            <th>Username</th>
            <td> {{user.username}} </td>
        </tr>
        <tr>
            <th>First Name</th>
            <td> {{user.first_name}} </td>
        </tr>
        <tr>
            <th>Last Name</th>
            <td> {{user.last_name}} </td>
        </tr>
        <tr>
            <th>Email</th>
            <td> {{user.email}} </td>
        </tr>

    </tbody>
</table>

<a href=" {%url 'studentapp:userupdate' user.id %}" class="btn btn-success btn-sm">Edit Profile</a>

<a href=" {% url 'studentapp:userchangepass' %} " class="btn btn-success btn-sm">Change Password</a>



<br> {% endblock body_block %}

crudproject2/templates/studentapp/signup.html
{% extends 'studentapp/base.html' %} {% block body_block %}
 {%if messages%}
<div class="alert alert-danger alert-dismissible mb-3">
    <button type="button" class="close" data-dismiss="alert">&times;</button> {%for message in messages %} {{message}} {%endfor%}
</div>
{%endif%}


<h1 class="text-center my-3">Sign Up Page</h1>



<form action="" method="POST">
    {% csrf_token %}
    <!--  
    {% for fm in form %} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> {%endfor%}
     -->
    {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-success btn-sm">
</form>

<br> {% endblock body_block %}

crudproject2/templates/studentapp/studentdetails.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">This is Student Details page</h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Serial No</th>

            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Class</th>
            <th scope="col">Result</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
            <th scope="col">Phone</th>

            {% if user.is_superuser %}
            <th scope="col">Action</th>
            {% endif %}

        </tr>
    </thead>
    <tbody>
        {% for std_details in students_info %}
        
        <tr>
            
            <th scope="row">{{ forloop.counter }}</th>
            <th scope="row"> {{std_details.id}} </th>
            <td> {{std_details.name}} </td>
            <td> {{std_details.class_name}} </td>
            <td> {{std_details.result}} </td>
            <td> {{std_details.email}} </td>
            <td> {{std_details.address}} </td>
            <td> {{std_details.phone}} </td>

            {% if user.is_superuser %}
            <td class="d-flex">
                <a href=" {% url 'studentapp:updatestudent' std_details.id %} " class="btn btn-success btn-sm mr-2">Update</a>
                <a href=" {% url 'studentapp:deletestudent'  std_details.id %} " class="btn btn-danger btn-sm">Delete</a>
            </td>
            {% endif %}

        </tr>
        {%endfor%}
    </tbody>
</table>


{% endblock body_block %}

crudproject2/templates/studentapp/updatestudent.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">Update Student Page</h1>



<form action="" method="POST">
    {%csrf_token %} 
    
    {% for fm in form %} 
      {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br>
    {%endfor%}

    <input type="submit" value="Update" class="btn btn-success btn-sm my-2">
</form>




<br> {% endblock body_block %}

crudproject2/templates/studentapp/userchangepass.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">Password Change</h1>

<form action="" method="POST">


    {% csrf_token %} {% for fm in form %} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> {% endfor %}
    <input type="submit" value="Save" class="btn btn-success btn-sm">
</form> <br>






<br> {% endblock body_block %}

crudproject2/templates/studentapp/userprofileupdate.html
{% extends 'studentapp/base.html' %} {% block body_block %}

<h1 class="text-center my-3">Update Profile</h1>


<form action="" method="POST">
    {%csrf_token %} {% for fm in form %} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br> {%endfor%}
    <input type="submit" value="Update" class="btn btn-success btn-sm my-3">
</form>



<br> {% endblock body_block %}