My_Second_Project/Login_app/urls.py
from xml.dom.minidom import Document
from django.conf import settings
from django.urls import re_path as url   #from django.conf.urls import url   (this was in django version 3)
from django.urls import path
from Login_app import views

from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


app_name = 'Login_app'

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('register/' , views.register , name = 'register'),
    path('login/' , views.login_page , name = 'login'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('logout/' , views.user_logout , name = 'logout'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

My_Second_Project/My_Second_Project/urls.py

from django.contrib import admin
from django.urls import path  ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('Login_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User  # import User model from django authorization(administration) ........
# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)  # blank =True mane chaile ai field ti blank rakhte parbe.....
    profile_pic = models.ImageField(upload_to = 'profile_pics' , blank=True)

    def __Str__(self):
        return self.user.username


My_Second_Project/Login_app/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.models import User  # import User model from django authorization(administration) ........
from Login_app.models import UserInfo 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User  # User holo django admin ar akti model .......
        fields = ('username' , 'password','email')  # ai field gulo User model ar built in field.......
        widgets = {
            'username' : forms.TextInput(attrs={'class':'form-control'}),
            'password' : forms.PasswordInput(attrs={'class':'form-control'}),
            'email' : forms.EmailInput(attrs={'class':'form-control'}),
            
        }
      
class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id' , 'profile_pic')
        widgets = {
            'facebook_id' : forms.TextInput(attrs={'class':'form-control'}),
            'profile_pic' : forms.FileInput(attrs={'class' : 'form-control'}),
            
        }

My_Second_Project/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import * # importing all forms from Login_app
from Login_app.models import UserInfo
from django.contrib.auth.models import User


from django.contrib.auth import authenticate ,login  ,logout  # for authenticated login and logout......
from django.http import HttpResponseRedirect ,HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def login_page(request):
    return render(request , 'Login_app/login.html' ,context={})


def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username , password =password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index')) 

            else:
                return HttpResponse("Account is not active!!")

        else:
            return HttpResponse("Login details are wrong")

    else:
        HttpResponseRedirect(reverse('Login_app:login'))




@login_required       # if user is not logged in he can't see logout option......
def user_logout(request):     
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))




def index(request):
    dict = {}
    if request.user.is_authenticated:  # if user is logged in
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        dict = {'user_basic_info' : user_basic_info, 'user_more_info' : user_more_info}


    
    return render(request , 'Login_app/index.html'  ,context= dict)


def register(request):
    registered = False
     
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()          # user_form ar data gulo save kore abar saved datagulo user object a rekheci
            user.set_password(user.password) # user object a password field ar password tike encrypt koreci
            user.save()                      # then setike abar save koreci. avabe password encrypted hoyeche

            
            # user_info_form a thaka data gulo save kore user_info object a rekheci.but commit = False ar karone database a data save hobe na
            user_info = user_info_form.save(commit=False) 
            user_info.user = user     # ai line tar kaj ki???????????

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            

            user_info.save()

            registered = True


    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()


    dict = {'user_form' : user_form   , 'user_info_form' : user_info_form  ,  'registered' : registered}
    return render(request , 'Login_app/register.html' , context=dict)


My_Second_Project/templates/Login_app/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title> {{title}} </title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="">Comilla Victorians</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href=" {% url 'Login_app:index'  %}  ">Home</a>
                </li>
                {% if user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link" href=" {% url 'Login_app:logout'  %}  ">Logout</a>
                </li>
                {% else %}

                <li class="nav-item active">
                    <a class="nav-link" href=" {% url 'Login_app:register'  %}  ">Register</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href=" {% url 'Login_app:login'  %}  ">Login</a>
                </li>
                {% endif %}



            </ul>

        </div>
    </nav>

    <div class="container pt-5">

        {% block body_block %} {% endblock %}


    </div>



    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

</body>

</html>

My_Second_Project/templates/Login_app/index.html
{% extends 'Login_app/base.html' %} {% block body_block %} {% if user.is_authenticated%}

<p>Hi {{user_basic_info.username}} </p>
<p>Your Email: {{user_basic_info.email}} </p>
<p>
    <a href="{{user_more_info.facebook_id}} "> Facebook Profile </a>
</p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" alt="user profile pic"> {% else %}
<div class="alert alert-primary">You are not logged in !</div>
{% endif %} {% endblock %}

My_Second_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %} {% block body_block %}

<h3>Please Login:</h3>

<form method="POST" action="{%  url 'Login_app:user_login'%}">
    <label for="username">Username</label>
    <input type="text" class="form-control" name="username" placeholder="Enter Username.." required>

    <label for="password">Password</label>
    <input type="password" class="form-control" name="password" required placeholder="Enter Password..">

    <br>{% csrf_token %}
    <input type="submit" class="btn btn-success btn-sm" name="submit" value="Login">

</form>



{% endblock %}

My_Second_Project/templates/Login_app/register.html
{%extends "Login_app/base.html"%} {%load static%} {%block body_block%}
<!---
if I want to upload file using a form then i have to add
enctype="multipart/form-data"     into form tag
-->
{% if registered %}
<div class="alert alert-success">
    Congratulations ! Registration Successfull!
</div>

{%else%}
<form enctype="multipart/form-data" method="POST">
    {{user_form.as_p}} {{user_info_form.as_p}} {% csrf_token %}
    <input type="submit" class="btn btn-success" name="submit" value="Register">
</form>


{% endif %} {% endblock %}